FROM python:3.9.15
WORKDIR /app
RUN mkdir /app/data && mkdir /app/src 
COPY requirements-snc.txt .
RUN --mount=type=cache,target=/root/.cache/pip \
    python3 -m pip install --upgrade pip setuptools wheel && \
    python3 -m pip install -r requirements-snc.txt
COPY . . 
CMD ["python3", "snc.py"]